#pragma once


#define COMMAND_PACKET_RECEIVED 0x01
#define COMMAND_STATUS_UPDATE   0x02
#define COMMAND_PAUSE			0x02
#define COMMAND_CONTINUE		0x03
#define COMMAND_STNDBYMODE		0x04
#define COMMAND_TEST_CON		0x05
#define COMMAND_GPIO_OP			0x06
#define COMMAND_NO_OP			0x07
#define COMMAND_FFLUSH			0x08
#define COMMAND_DEBUG_DATA		0x09
#define COMMAND_SAVE_DATA		0x0A
#define COMMAND_PING			0x0B

#define REQUEST_ALL_DATA		0xF1
#define REQUEST_TEST_DATA		0xF2
#define REQUEST_TEMP_DATA		0xF3
#define NO_COMMAND				0xFF


#define SETTING_SET				0x40
#define SETTING_GET				0x41
#define SETTING_SMPL_BUF_SIZE	0x50
#define SETTING_USB_BUF_SIZE	0x51
#define SETTING_DEBUG_MODE		0x52
#define SETTING_FLASH_MODE		0x53

#define OFF						0x00
#define ON						0x01